---
- name : Deployment in EC2 instances using Ansible (no jenkins at all)
  hosts : dev
  user : ubuntu
  become : yes

  vars:
    IMAGE : 'tejaswi4268/myproject'
    TAG : 'latest'
    CONTAINER_NAME : 'my-own-container'

  tasks :
    - name : Update and Upgrade ubuntu machine
      apt :
        update_cache : yes
        force_apt_get : yes

    - name : Install dependencies for docker (required for using official docker stable version)
      apt :
        name :
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name : Add GPG Key for official docker repository to your system
      apt_key :
        url : https://download.docker.com/linux/ubuntu/gpg
        state : present

    - name : Add docker repository to apt resources
      apt_repository :
        repo : deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state : present

    - name : Install docker from Docker repo instead of the default Ubuntu repo
      apt :
        name : docker-ce
        state : present
        update_cache : yes
    
    - name : Start Docker service
      systemd :
        name : docker
        state : started
        enabled : yes

    - name : Pull Custom Image from my dockerhub
      shell : docker pull {{IMAGE}}:{{TAG}} 

    - name : Remove any container running with same name but old version
      shell : |
        docker stop {{CONTAINER_NAME}} || true
        docker rm -f {{CONTAINER_NAME}} || true

    - name : Run docker container on slave EC2 instance
      shell : docker run -d --name {{CONTAINER_NAME}} -p 8080:80 {{IMAGE}}:{{TAG}}

    


