pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials("aws-access-key") 
        AWS_SECRET_ACCESS_KEY = credentials("aws-secret-key")
    }

    stages {
        stage ("checkout scm") {
            steps {
                git "https://github.com/tejaswi-teju/myproject.git"
            }

        }

        stage('Debug') {
            steps {
                sh 'pwd'
                sh 'ls -lrt'
            }
        }

        stage ("Terraform init") {
            steps{
                dir("terraform.tf") {
                sh "terraform init"
                }
            }
        }

        stage ("Terraform fmt & validate") {
            steps {
                sh "cd terraform.tf && terraform fmt && terraform validate"
            }
        }

        stage ("terraform plan") {
            steps {
                sh "cd terraform.tf && terraform plan"
            }
        }

        stage ("Terraform apply") {
            steps {
                input message: "Proceed with terraform apply ?"
                sh "cd terraform.tf && terraform apply --auto-approve"
            }
        }

        stage ("Terraform destroy") {
            steps {
                sh "cd terraform.tf && terraform destroy --auto-approve"
            }
        }
    }
    
    
    post {
        success {
            echo "Build successful. Infra launched through Terraform"
        }
    }
}